"""
Integration tests for document loader.

Tests the loading of markdown files from the filesystem and extraction
of frontmatter metadata.
"""

import pytest
from pathlib import Path
from src.ingestion.document_loader import load_document, load_corpus


def test_load_single_file_extracts_frontmatter():
    """Test loading a single markdown file and extracting frontmatter fields."""
    # Given
    corpus_path = Path("data/corpus")
    test_file = corpus_path / "01_technical_infrastructure.md"
    
    # When
    document = load_document(test_file)
    
    # Then
    assert document.content is not None
    assert document.metadata["version"] == 1
    assert document.metadata["title"] == "Technical Infrastructure Documentation"
    assert "technical" in document.metadata["tags"]
    assert "---" not in document.content  # Frontmatter should be stripped from content


def test_generate_document_id_from_title():
    """Test that document_id is generated by slugifying the title."""
    # Given
    corpus_path = Path("data/corpus")
    test_file = corpus_path / "01_technical_infrastructure.md"
    
    # When
    document = load_document(test_file)
    
    # Then
    assert document.document_id == "technical-infrastructure-documentation"
    assert document.document_id.islower()
    assert " " not in document.document_id


def test_load_all_corpus_documents():
    """Test loading all documents from the corpus directory."""
    # Given
    corpus_path = Path("data/corpus")
    
    # When
    documents = load_corpus(corpus_path)
    
    # Then
    assert len(documents) == 4  # We have 4 markdown files in corpus
    assert all(isinstance(doc.document_id, str) for doc in documents)
    assert all(doc.content for doc in documents)
    assert all(doc.metadata for doc in documents)
    
    # Verify all documents have required metadata
    for doc in documents:
        assert "version" in doc.metadata
        assert "title" in doc.metadata


def test_raise_error_when_version_missing():
    """Test that an error is raised when version field is missing."""
    # Given - create a temporary file without version
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
        f.write("---\n")
        f.write("title: Test Document\n")
        f.write("---\n")
        f.write("# Content\n")
        temp_path = Path(f.name)
    
    try:
        # When/Then
        with pytest.raises(ValueError, match="Missing required frontmatter field: version"):
            load_document(temp_path)
    finally:
        temp_path.unlink()


def test_raise_error_when_title_missing():
    """Test that an error is raised when title field is missing."""
    # Given - create a temporary file without title
    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.md', delete=False) as f:
        f.write("---\n")
        f.write("version: 1\n")
        f.write("---\n")
        f.write("# Content\n")
        temp_path = Path(f.name)
    
    try:
        # When/Then
        with pytest.raises(ValueError, match="Missing required frontmatter field: title"):
            load_document(temp_path)
    finally:
        temp_path.unlink()
